Change current categry implementation:
- add env, PBJ_CURRENT_CATEGORY exported for subshell use
- pbj bash script: branch for -cu option completed
- pbj.py: branch for -cu option tested for command flaws
- change variable name in pbj bash script

diff --git a/pbj b/pbj
--- a/pbj
+++ b/pbj
@@ -1,9 +1,61 @@
 #!/usr/bin/env bash
+export PBJ_CURRENT_CATEGORY
   pbj() {
 	# Get the parent dir of this script, and resolve '/pbj.py'
 	# PARENT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
-	PARENT_DIR=$(dirname "$(realpath "${BASH_SOURCE[0]}")")
-	pbjpy="$PARENT_DIR/pbj.py"
+	PBJ_PARENT_DIR=$(dirname "$(realpath "${BASH_SOURCE[0]}")")
+	pbjpy="$PBJ_PARENT_DIR/pbj.py"
+	
+	# if arg1 starts with '-test' (test for change current category)
+	if [[ $1 == "-test" ]]; then
+		pbj_output="$($pbjpy $@)"
+		read -a output_array <<< "$pbj_output"
+		#output_array=($pbj_output)
+		pbj_env=${output_array[0]}
+		pbj_dir=$([[ -n ${output_array[1]} ]] && echo ${output_array[1]} || echo "")
+
+		if [[ -n $pbj_env ]] && [[ -d $pbj_dir ]]; then
+			export PBJ_CURRENT_CATEGORY="$pbj_env"
+			cd "$pbj_dir"
+			return 0
+		fi
+		return 1
+	fi
+
+	# if arg1 starts with '-cu' (change current category)
+	if [[ $1 == "-cu" ]]; then
+		pbj_output="$($pbjpy "$@")"
+		read -ra output_array <<< "$pbj_output"
+		pbj_env=""
+		pbj_dir=""
+		num_args="${#output_array[@]}"
+
+		#TESTS: 
+		echo $pbj_output
+		echo ${output_array[*]}
+		echo "num_args: $num_args"
+
+		if [[ $num_args == 1 ]]; then
+			pbj_env="${output_array[0]}"
+			if [[ -n $pbj_env ]]; then
+				export PBJ_CURRENT_CATEGORY=$pbj_env
+				return 0
+			else
+				echo "change of current category failed"
+			fi
+			return 1
+		elif [[ $num_args == 2 ]]; then
+			pbj_env="${output_array[0]}"
+			pbj_dir="${output_array[1]}"
+			if [[ -n $pbj_env ]] && [[ -d $pbj_dir ]]; then
+				export PBJ_CURRENT_CATEGORY=$pbj_env
+				cd $pbj_dir || return 0
+			else
+				echo "change of current category and change directory failed"
+				return 1
+		fi
+		return 0
+	fi
 	
 	# if arg1 starts with dash, run in this shell
 	if [[ ${1:0:1} == "-" ]]; then
